void black2alpha_ps(
   //in
   float2 uv: TEXCOORD0,
   uniform sampler2D texture,
   //out
   out float4 oColor : COLOR
)
{
   oColor = tex2D(texture, uv);
   oColor.a = oColor.r;   
   
	//if (oColor.r < 0.5) oColor.r = oColor.r*2;
	//if (oColor.b < 0.5) oColor.r = oColor.b*2;
	oColor.b = oColor.b*2;
	
	if (oColor.r > 0.0 && oColor.r < .05) {	
		oColor.r = 0.6; 
		oColor.b = 0.1; 
		oColor.g = 0.8; 
	}
} 
